global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'protheus-python-exporter'
    static_configs:
      - targets: ['protheus-exporter:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'protheus-native-exporter'
    static_configs:
      - targets: ['seu-servidor-protheus:porta']
    metrics_path: '/rest/protheus_exporter/'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']